apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: gcr.io/cicd-project-438005/flaskapp/flaskapp:latest  # Image from Container Registry
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
